apiVersion: v1
kind: Namespace
metadata:
  name: ns-2048
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-2048
  namespace: ns-2048
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-2048
  template:
    metadata:
      labels:
        app: app-2048
    spec:
      containers:
      - name: pod-2048
        image: evilroot/docker-2048
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service-2048
  namespace: ns-2048
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: app-2048
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: virtualservice-2048
  namespace: ns-2048
spec:
  hosts:
  - "2048.k8s.vpn"
  gateways:
  - istio-system/istio-ingressgateway
  http:
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: service-2048
        port:
          number: 80
